version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ${SCRIPT_DIR}/api:/app
    env_file:
      - .env